##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
cuboid:
  table:
    dims: [0.015, 0.015, 0.5] # x, y, z
    pose: [0.25, 0.0, 0.25, 0, 0, 0, 1] # x, y, z, qx, qy, qz, qw                                                                                                                                                                                                                                                            